package com.mongodb.week2;

import java.util.Arrays;

import org.bson.Document;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.week2.helpers.Helpers;

public class InsertTest {

	// _id is generated by the driver on client and inserted into the document before the document is inserted into the DB
	public static void main(String[] args) {
		MongoClient client = new MongoClient(new MongoClientURI("mongodb://localhost:27017"));
		MongoDatabase testDb = client.getDatabase("test");
		MongoCollection<Document> crudTest = testDb.getCollection("crudTest");
		crudTest.drop();
		
		Document smith = new Document().append("name", "Smith")
										.append("age", 30)
										.append("profession", "programmer");
		Helpers.printJson(smith, true);
		
		crudTest.insertOne(smith);
		
		smith.remove("_id");	//removes the _id attribute from the document map
		
		crudTest.insertOne(smith);	//insert the documnet again with new id
		
		Helpers.printJson(smith, true);
		
		Document jones = new Document().append("name", "Jones")
				.append("age", 32)
				.append("profession", "hacker");
		
		Document mike = new Document().append("name", "Mike")
				.append("age", 34)
				.append("profession", "tester");

		crudTest.insertMany(Arrays.asList(jones, mike));
		
		client.close();

	}

}
